name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add emacs PPA
      run: sudo add-apt-repository -y ppa:kelleyk/emacs
    - name: Install Emacs
      run: sudo apt-get update && sudo apt-get install -y xvfb emacs26
    - uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install Cask
      uses: conao3/setup-cask@master
      with:
        version: 'snapshot'
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install package dependencies
      run: |
        cask install
    - name: Compile
      run: |
        cask build
    - name: Run tests
      run: |
        xvfb-run --auto-servernum cask exec ert-runner --win
      env:
        CI: true
    - name: Cleanup xvfb pidx
      uses: bcomnes/cleanup-xvfb@v1
